### ISSUE TITLE
Broken Text Rendering

### ISSUE THREAD

**Issue by MasterEnderman** [blahthebiste/NetherSky#1]
Thanks for this great mod.

Sadly after adding it to my pack I encountered a few issues related to text rendering. I know that a modpack is a heavily altered environment, but I like to use it nonetheless. I can't really pin point which mod interaction causing this, if it's an interaction at all. Below are a few examples of the issues related to text rendering. Like stated before those only occur if I add NetherSky to the pack and resume to function normally, when it's removed again.

Server Information Thingy
![image](https://github.com/user-attachments/assets/f2e99562-c2ef-4349-a1ba-0ec20c87eb9f)

Ingame Chat (I actually typed =457  and when sending the message it actually displays as =457, so it's only the chat input itself)
![image](https://github.com/user-attachments/assets/c540cd06-4c0c-4b38-bd1f-dc9957a4bab9)

Sign Editing GUI (Quark)
![image](https://github.com/user-attachments/assets/e84a47d2-c5ef-44c8-b217-d2442e312e82)
When I move my cursor to the end of the line it returns to normal
![image](https://github.com/user-attachments/assets/fa43aa01-a1ea-4d30-8111-93352b6ae47a)

Formatting in Tooltips (the display of all the "§7"
![image](https://github.com/user-attachments/assets/a770e554-5a80-4f1e-b3b1-9205c9e22197)

**Comment by blahthebiste** [comment]
Fixed in 1.0.1
